<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_lG9Pv6D7a1</name>
   <tag></tag>
   <elementGuidId>14a3842b-d0c5-4321-9bbd-94f8c614160d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lG9Pv6D7a1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lG9Pv6D7a1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;lG9Pv6D7a1&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdcb61cf-1798-487e-9785-9ddc7119cef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lG9Pv6D7a1</value>
      <webElementGuid>ab0beb5a-d54a-4c81-badd-79bde67fba9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lG9Pv6D7a1</value>
      <webElementGuid>9ce375d3-2ba8-4bc7-ac59-dc2a1b89591d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lG9Pv6D7a1&quot;)</value>
      <webElementGuid>31136b57-ef9f-42e7-a77a-a8bc4c2f4f7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lG9Pv6D7a1']</value>
      <webElementGuid>d2282db7-527c-4aa0-ae30-d6d9b95c4a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/input[4]</value>
      <webElementGuid>e40992d7-25b3-44ee-94cf-964ccb1c3cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>2871c815-3b46-4927-abcd-6496294ae034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lG9Pv6D7a1' and @name = 'lG9Pv6D7a1']</value>
      <webElementGuid>c6c90952-8813-4536-9a92-a6f8c8f9947a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
