<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mail_uOlyc1v</name>
   <tag></tag>
   <elementGuidId>9c748cef-7f6a-480b-8554-86518753f567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uOlyc1v</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uOlyc1v']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;uOlyc1v&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf31b7c6-41ab-4789-9256-a02a99f051fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uOlyc1v</value>
      <webElementGuid>a6266f5d-233f-4200-a40e-3d4933d5d105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uOlyc1v</value>
      <webElementGuid>f7b4fd44-b3da-49eb-8b5b-11cab7b6955e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uOlyc1v&quot;)</value>
      <webElementGuid>d6416a5c-eec9-4140-9136-f79f4558e7bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uOlyc1v']</value>
      <webElementGuid>8384f023-e5ed-4230-ac8a-845f86dea030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/input[3]</value>
      <webElementGuid>b40564fb-0c9b-419a-b96c-d3a33273099d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>1cdefda5-bf14-46bb-8358-3c5df5310ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uOlyc1v' and @name = 'uOlyc1v']</value>
      <webElementGuid>4b15174e-4f46-4687-8904-243763e2b454</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
