<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Daftar di sini_sebagai</name>
   <tag></tag>
   <elementGuidId>eb22820f-ca2e-4f6e-b7e7-17a3cc38a0d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sebagai</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sebagai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sebagai</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3cd0bcb2-e7f3-497b-97e6-a95222a9c769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sebagai</value>
      <webElementGuid>e124a4e6-6146-4e1c-9dd3-3f715a3daa64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select mt-5-2 font-14-r</value>
      <webElementGuid>26fc20e4-afbc-4d0a-ae8d-f4bcd0ccad62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>myFunction()</value>
      <webElementGuid>92d0f637-038f-4273-9990-5a0e9644e504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Owner
                            Staff
                        </value>
      <webElementGuid>1687e59b-af8d-43c8-8bb5-a071a9a9f7ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sebagai&quot;)</value>
      <webElementGuid>2bfa5be9-4077-4ae7-8c91-394313e8997e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sebagai']</value>
      <webElementGuid>5ebace04-70ad-4175-a017-518d95d8c0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body-content']/section/div/div/div/div/select</value>
      <webElementGuid>805ce98e-7278-458d-ac0e-cc4c01844b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inggris'])[1]/following::select[1]</value>
      <webElementGuid>11d7ed39-716f-4eee-a4fe-ba2feff6b938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::select[1]</value>
      <webElementGuid>c67a3c53-68db-4460-9957-8bc520e72202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail'])[1]/preceding::select[1]</value>
      <webElementGuid>35b21a95-cc36-4d19-92a0-9fcd4b673907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::select[1]</value>
      <webElementGuid>e49e82bc-cd02-46cd-84c2-4e45adad3784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6adc1e17-9956-4635-a7a9-c13e69c1d812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'sebagai' and (text() = '
                            Owner
                            Staff
                        ' or . = '
                            Owner
                            Staff
                        ')]</value>
      <webElementGuid>db285e80-6ac2-4386-9ecf-153e0977c3ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
