<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Daftar di sini_sebagai</name>
   <tag></tag>
   <elementGuidId>f0b68489-f7f7-4105-84ca-11455de4fda1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sebagai</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sebagai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sebagai</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>09a10a3f-ffc8-4a16-959f-f535e1b757de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sebagai</value>
      <webElementGuid>df93a39d-7da2-44c9-847f-eb7c43e6597b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select mt-5-2 font-14-r</value>
      <webElementGuid>3809eddf-8041-418d-b195-ba2d02eec024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>myFunction()</value>
      <webElementGuid>93226c3d-c045-4ab6-863c-7ade74724feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Owner
                            Staff
                        </value>
      <webElementGuid>d47bfdeb-6226-46db-9c3b-23503b4253d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sebagai&quot;)</value>
      <webElementGuid>64927a6f-3b26-487f-a5a1-f3409a58ac75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sebagai']</value>
      <webElementGuid>f5bf0426-f365-45f1-9fd2-aad8203f4ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='parent']/div/div/div/div/select</value>
      <webElementGuid>6b2c4683-abe2-49ea-8bd7-972bbc5f91fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar di sini'])[1]/following::select[1]</value>
      <webElementGuid>aaa7e894-1d5f-4cfe-98f8-19b8f2a7b0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inggris'])[1]/following::select[1]</value>
      <webElementGuid>dcb359e5-db93-4010-8005-d98f61dae625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/preceding::select[1]</value>
      <webElementGuid>d43f9be6-7dd1-40b6-ad92-28a7c547bf8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password?'])[1]/preceding::select[1]</value>
      <webElementGuid>8ee9dd1c-d056-413f-83bc-18eb2bde5577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f91e09b5-46d3-4fcb-8a3d-48521b478e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'sebagai' and (text() = '
                            Owner
                            Staff
                        ' or . = '
                            Owner
                            Staff
                        ')]</value>
      <webElementGuid>ae15f5d3-15d2-4779-a014-178c1baba167</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
