<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Inggris_font-32-sb font-black</name>
   <tag></tag>
   <elementGuidId>2a971d43-9b56-4590-a4f6-8a3a7d078488</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.font-32-sb.font-black</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='parent']/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Login Owner&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>475490b0-bfa4-428b-bacb-532c55de9980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-32-sb font-black</value>
      <webElementGuid>d326dc30-5a52-4747-a2b8-6e7ef39c57a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>d8ebeb42-edf8-43db-b77c-75f104d3870c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login Owner</value>
      <webElementGuid>92ce6c5e-ad9e-4010-a054-960d02cd8429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;parent&quot;)/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-lg-6&quot;]/div[@class=&quot;px-50&quot;]/p[@class=&quot;font-32-sb font-black&quot;]</value>
      <webElementGuid>3fc661b9-16aa-43ef-a395-369d6b33a380</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='parent']/div/div/div/p</value>
      <webElementGuid>bc063562-d9b2-4f26-b9fb-0aa3c3a51061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inggris'])[1]/following::p[1]</value>
      <webElementGuid>27b06c6a-50a5-4dfa-95ff-97f1b9629dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::p[1]</value>
      <webElementGuid>cbcbccd3-1704-4832-92a2-9f755f19f7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar di sini'])[1]/preceding::p[1]</value>
      <webElementGuid>76b89e2d-db8e-48f5-b271-b551c8007f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/preceding::p[6]</value>
      <webElementGuid>9262cc40-7f49-4959-9880-bcf1302d9bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login Owner']/parent::*</value>
      <webElementGuid>7632ef44-66d3-44d3-bcfa-a6ab14b3d822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/p</value>
      <webElementGuid>5d12ef49-03d5-4369-adc6-a862dbc67c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Login Owner' or . = 'Login Owner')]</value>
      <webElementGuid>e3a823f7-a588-47a2-9d6c-d23b5c188f50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
