<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Daftar di sini_sebagai</name>
   <tag></tag>
   <elementGuidId>7aa0c1ea-2e75-479f-8de3-0155ee6c370d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sebagai</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sebagai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sebagai</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>30033f98-b6b3-4e77-82c5-bd954d9a5aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sebagai</value>
      <webElementGuid>d799b89a-a2c2-4d7d-8dfb-4707404c384e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select mt-5-2 font-14-r</value>
      <webElementGuid>5ac2a46f-9b81-4fea-a374-bbc6c1fcacfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>myFunction()</value>
      <webElementGuid>106cdbf4-d384-4200-bbfa-feeb5797de4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Owner
                            Staff
                        </value>
      <webElementGuid>ce89292a-7e50-4b6e-89b7-554065d16315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sebagai&quot;)</value>
      <webElementGuid>9cf36cd4-c51e-49f1-85d8-97819b6b8841</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sebagai']</value>
      <webElementGuid>a6a2001d-b793-4eaf-a279-f7be8e458ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='parent']/div/div/div/div/select</value>
      <webElementGuid>31a70633-efb3-4b85-9755-a5a0d7f65bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar di sini'])[1]/following::select[1]</value>
      <webElementGuid>0c8e25c4-29d5-492e-856f-3f5689ec1472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inggris'])[1]/following::select[1]</value>
      <webElementGuid>81fa0022-9186-496c-b5a4-644ed4302954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/preceding::select[1]</value>
      <webElementGuid>65adeb55-b15f-417e-a788-ea3db28bb371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password?'])[1]/preceding::select[1]</value>
      <webElementGuid>445d66f1-bdac-4709-b085-7abbabc2aecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>fe0e862f-808b-4246-bc9e-75a58adf25f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'sebagai' and (text() = '
                            Owner
                            Staff
                        ' or . = '
                            Owner
                            Staff
                        ')]</value>
      <webElementGuid>5ed121ac-ab92-4424-aa80-41e6e1413326</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
