<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Page Harga_Button Download Kasir Pintar PRO</name>
   <tag></tag>
   <elementGuidId>b50cd2dc-0cdb-43c7-9745-aa47a9318346</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_pro_price_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_pro_price_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ae4fa776-91d3-430d-a9eb-5d174cabf8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_pro_price_2</value>
      <webElementGuid>7d966941-e750-487a-95b5-25571f07c15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://kpntr.link/download_pro_website?utm_source=web&amp;utm_medium=landing_page_price&amp;utm_campaign=button2</value>
      <webElementGuid>f80c2107-699d-42ef-aac5-0ee24f3b2e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>308f0792-8e08-4b82-85a7-26a73ecdf171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button-download-pro mt-10 rounded-pill font-20-sb</value>
      <webElementGuid>2e91c3ec-510a-4327-8b2d-daf845acc849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download Sekarang</value>
      <webElementGuid>bee30bd3-4844-48fe-8416-69499e5dc1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_pro_price_2&quot;)</value>
      <webElementGuid>cc9ae290-a9e6-4ea1-8ac5-ea5ef6527468</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_pro_price_2']</value>
      <webElementGuid>b539ad31-9563-44e3-ad4d-4b180385f6cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body-content']/section/div/div/div[3]/a</value>
      <webElementGuid>f2f9c4a7-c85d-4b44-b975-f22fd2a28d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Download Sekarang')])[2]</value>
      <webElementGuid>fef50764-7e9b-4f68-b3ae-ea0867756f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi-User (Hingga 5 Akun Staff)'])[1]/following::a[1]</value>
      <webElementGuid>20ef9973-034b-4555-9d36-5c93dee91dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Struk tanpa watermark'])[1]/following::a[1]</value>
      <webElementGuid>2631d11f-f798-4745-8567-7c663ae99edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/preceding::a[1]</value>
      <webElementGuid>5550eb2c-993b-41fc-aacc-422e84eccc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://kpntr.link/download_pro_website?utm_source=web&amp;utm_medium=landing_page_price&amp;utm_campaign=button2']</value>
      <webElementGuid>5386203e-67e8-4e5c-956b-be55b2984b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>899be16c-ea21-4627-976f-42a23f6495dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_pro_price_2' and @href = 'http://kpntr.link/download_pro_website?utm_source=web&amp;utm_medium=landing_page_price&amp;utm_campaign=button2' and (text() = 'Download Sekarang' or . = 'Download Sekarang')]</value>
      <webElementGuid>1b0b32be-eee4-42bf-bdde-abb8aaa868d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
