<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Produk Kasir Pintar Pro</name>
   <tag></tag>
   <elementGuidId>7602daa2-5eb2-4d82-b15e-e7bbe67fad18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_free_navbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_free_navbar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8cca5f56-cb24-4078-bc08-2d408e030dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item font-14-r font-gray mbt-10</value>
      <webElementGuid>ce56440e-aa4a-40e0-a0ee-0a5b2684407c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_free_navbar</value>
      <webElementGuid>b7b45976-1406-4b5a-aff6-8a2d892da19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://kpntr.link/download_pro_website?utm_source=web&amp;utm_medium=landing_page_navbar&amp;utm_campaign=download_pro</value>
      <webElementGuid>6342c63e-5535-42c6-96b3-aa7882e55446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>0ca399ce-e2e0-4896-9665-ae4f1903b1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kasir Pintar Pro</value>
      <webElementGuid>e5ae7d9c-5a5d-4a7c-9a0b-459846d12df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_free_navbar&quot;)</value>
      <webElementGuid>3c7910dc-4946-4e09-a7c1-189fe440628c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_free_navbar']</value>
      <webElementGuid>46caaef3-23a3-4d79-b2fb-039a1c57c93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarTogglerDemo02']/ul/li[3]/div/div/div/ul/li[2]/a</value>
      <webElementGuid>895822e8-5972-49d7-b835-3979b6376d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kasir Pintar Pro')]</value>
      <webElementGuid>e4c1a63c-6d3d-45f6-b710-a504bae51d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kasir Pintar Free'])[1]/following::a[1]</value>
      <webElementGuid>86b22c9a-da35-4d50-9d6d-2e4bf86f68c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bengkel'])[1]/following::a[3]</value>
      <webElementGuid>e6b36d16-7934-4307-aeb0-062182ecee46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kasir Pintar Desktop'])[1]/preceding::a[2]</value>
      <webElementGuid>1b19df3d-d04e-46aa-9f11-3d7fafd74a89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kasir Pintar Pro']/parent::*</value>
      <webElementGuid>3421c6ae-c1b1-4813-adcd-1e1618983a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://kpntr.link/download_pro_website?utm_source=web&amp;utm_medium=landing_page_navbar&amp;utm_campaign=download_pro']</value>
      <webElementGuid>5002a31e-1bbe-4815-95d8-f65273ed0134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[2]/a</value>
      <webElementGuid>b7024a9d-88e9-495b-a3f6-eaa42ff8e808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_free_navbar' and @href = 'http://kpntr.link/download_pro_website?utm_source=web&amp;utm_medium=landing_page_navbar&amp;utm_campaign=download_pro' and (text() = 'Kasir Pintar Pro' or . = 'Kasir Pintar Pro')]</value>
      <webElementGuid>825c5f06-4d4d-4273-86f2-5bece6ef8c24</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
