<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Daftar Navbar</name>
   <tag></tag>
   <elementGuidId>b32f2689-c5fe-4b1a-9d03-0f39f21835d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_reg_navbar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_reg_navbar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6dee3875-2b8a-4c73-a1be-ac97094e9ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> m-log  font-14-sbb btn button-green-daftar text-uppercase font-white mrd-10</value>
      <webElementGuid>6e854d31-a09f-4af6-bded-16ea623ffe3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_reg_navbar</value>
      <webElementGuid>d9d51dbb-aa5f-40ae-b08c-3066da03d5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://laravel-qa.kpntr.com/register?utm_source=web&amp;utm_medium=top_navbar&amp;utm_campaign=button1</value>
      <webElementGuid>012a063e-4386-4a63-b6fa-01c352a1b059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar</value>
      <webElementGuid>68099924-5137-4a04-9cde-76319a10daa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_reg_navbar&quot;)</value>
      <webElementGuid>4ad7e8db-8cf7-41ac-9376-70ec19b0239c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_reg_navbar']</value>
      <webElementGuid>782132dc-f3e5-4ed3-94f9-15d594e7ad89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarTogglerDemo02']/ul/li[7]/a</value>
      <webElementGuid>763cccb6-ec41-4562-ad6e-c7c74d82450e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Daftar')]</value>
      <webElementGuid>f17c5928-5607-48a4-bf34-bd43d78d7b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Blog'])[1]/following::a[1]</value>
      <webElementGuid>e8a78c7c-0073-4250-8dde-08a9a76558ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solusi'])[1]/following::a[2]</value>
      <webElementGuid>443606e3-8b1a-420a-9d1c-41721f4dadda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::a[1]</value>
      <webElementGuid>76e7ff39-b0e3-4683-bf1c-b63e9989131d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/preceding::a[3]</value>
      <webElementGuid>d430d2b3-dc56-44d6-b8be-4f139de18434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar']/parent::*</value>
      <webElementGuid>458c715a-c2ba-45f5-be08-547659a72c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://laravel-qa.kpntr.com/register?utm_source=web&amp;utm_medium=top_navbar&amp;utm_campaign=button1')]</value>
      <webElementGuid>c947245f-026d-4180-82f9-12484e7346c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>664f9ebb-6d7f-4910-9820-57b0b4a59117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_reg_navbar' and @href = 'https://laravel-qa.kpntr.com/register?utm_source=web&amp;utm_medium=top_navbar&amp;utm_campaign=button1' and (text() = 'Daftar' or . = 'Daftar')]</value>
      <webElementGuid>c983884c-6816-4463-960e-8fdc5180ace6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
