<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button Register CTA Marketing</name>
   <tag></tag>
   <elementGuidId>8968d165-f23d-4826-9093-853dfd7841dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_reg_home</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_reg_home']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7aab7aba-c469-4ed6-813f-c93b5e97d6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://laravel-qa.kpntr.com/registerpro?utm_source=web&amp;utm_medium=home&amp;utm_campaign=buttonslider1</value>
      <webElementGuid>652c9d65-a7a3-43cd-8889-4b32b4b75f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_reg_home</value>
      <webElementGuid>35b4925d-9047-47f3-851e-6febf5f78561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button-white-green border-0 font-18-b font-green-2 rounded-pill h-48 btn-w-head</value>
      <webElementGuid>1e94399f-9392-4f51-92f1-75da30ebb2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>beaf4933-ab08-4a80-a55f-119c3a270db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Coba Gratis 30 Hari</value>
      <webElementGuid>36e7a5f4-409a-4743-ac73-93e4bde687f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_reg_home&quot;)</value>
      <webElementGuid>11c858b4-4ee9-4628-b54f-74688a1bd3ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_reg_home']</value>
      <webElementGuid>6a861b79-3ea6-4e5a-9734-def4a18d5be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slick-slide00']/div/div/div/a</value>
      <webElementGuid>7bf06126-f8c4-4d99-b127-6756eb283f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Coba Gratis 30 Hari')]</value>
      <webElementGuid>348bd0e3-7473-44bd-82e8-fd775edcd6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Coba Gratis 30 Hari']/parent::*</value>
      <webElementGuid>24f683f9-1233-4e39-b9f5-065b662651eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://laravel-qa.kpntr.com/registerpro?utm_source=web&amp;utm_medium=home&amp;utm_campaign=buttonslider1')]</value>
      <webElementGuid>0566eecd-d8f5-484f-b2ae-0d914a76d3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>ae55c44f-8a3a-4188-bb30-eca95c3397a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://laravel-qa.kpntr.com/registerpro?utm_source=web&amp;utm_medium=home&amp;utm_campaign=buttonslider1' and @id = 'btn_reg_home' and (text() = 'Coba Gratis 30 Hari' or . = 'Coba Gratis 30 Hari')]</value>
      <webElementGuid>ce9e62d5-f329-46bf-91a1-b545491d5a76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
