<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Title Page Register</name>
   <tag></tag>
   <elementGuidId>ec761d94-375e-4816-a9cf-ba915353b52e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.font-32-sb.font-black</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='body-content']/section/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c799ff5c-9574-47c5-a77c-b0b61ce67062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-32-sb font-black</value>
      <webElementGuid>4a2d2879-c7a0-4433-8c9b-cfa7113893ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>ccfd6e30-c5ec-4160-99e9-bf6c0819d469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Akun</value>
      <webElementGuid>ba3a226c-63a0-4ec0-8dc7-fecc7a745dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-content&quot;)/section[@class=&quot;pt-120-2 pb-64 bg-white&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-lg-7&quot;]/p[@class=&quot;font-32-sb font-black&quot;]</value>
      <webElementGuid>33717ffd-70fb-4733-9d50-b17da467ef3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body-content']/section/div/div/div/p</value>
      <webElementGuid>e51c6fb6-86bb-45ed-8dc0-836a2206125f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inggris'])[1]/following::p[1]</value>
      <webElementGuid>a9283a75-930c-4829-aaf5-e48af3723c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[1]/following::p[1]</value>
      <webElementGuid>e8b52401-31f7-4708-ab61-1e377d3e1414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login di sini'])[1]/preceding::p[1]</value>
      <webElementGuid>a9a9ad29-7c3f-4858-8b13-0ed7771b4398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hubungi CS'])[1]/preceding::p[6]</value>
      <webElementGuid>d7efb657-992d-46cc-a2c6-98a9abd491d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Daftar Akun']/parent::*</value>
      <webElementGuid>2762d5fd-3d94-4031-9e5f-1413be284c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/p</value>
      <webElementGuid>54079db0-82ca-408a-a40e-43960493d7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Daftar Akun' or . = 'Daftar Akun')]</value>
      <webElementGuid>59e927e1-b6f8-4774-a9a9-e07a429139fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
