<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Daftar di sini_sebagai</name>
   <tag></tag>
   <elementGuidId>1b0627f6-b9f7-4e6b-8487-1a9b13856bf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sebagai</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sebagai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#sebagai</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b6382880-6cb2-4af4-847f-6006fbe478fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sebagai</value>
      <webElementGuid>636ecb67-5b35-4012-88bc-0d5317b9d1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select mt-5-2 font-14-r</value>
      <webElementGuid>694b28a6-5eb1-4087-878a-e08d770637f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>myFunction()</value>
      <webElementGuid>43161968-5e66-40f9-869b-8b900d9e02ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Owner
                            Staff
                        </value>
      <webElementGuid>130a7f08-e34f-4679-abf3-bfe5c3b838fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sebagai&quot;)</value>
      <webElementGuid>ace6c6df-9bf5-4551-a16e-81382201c444</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sebagai']</value>
      <webElementGuid>3d80765e-18c7-49f5-8303-35ee4bf117e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='parent']/div/div/div/div/select</value>
      <webElementGuid>3403e0a3-2b55-43d6-b48a-e218c8c28b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar di sini'])[1]/following::select[1]</value>
      <webElementGuid>072521ae-eac7-4668-8151-18887903c0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inggris'])[1]/following::select[1]</value>
      <webElementGuid>7e811255-e771-4d12-9e0c-dcfcd9e40465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/preceding::select[1]</value>
      <webElementGuid>13db7268-1baf-4efe-80b3-408adbdb8b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password?'])[1]/preceding::select[1]</value>
      <webElementGuid>2c6fed26-9097-4e6c-8b0d-ee55368f6679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b00b8158-82ea-4e68-98a3-6599ee7e8e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'sebagai' and (text() = '
                            Owner
                            Staff
                        ' or . = '
                            Owner
                            Staff
                        ')]</value>
      <webElementGuid>efdb2305-1d2a-415a-9505-39a0bd90791c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
