<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Form Input Upload Foto Barang</name>
   <tag></tag>
   <elementGuidId>15b6048c-d5bb-4cd2-b9b9-7f6a0e450730</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='imgSku']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#imgSku</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;icon&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>67d6678f-bf7f-402c-a92b-f6aa5bdd8e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/cdn/gambar/addimage_backoffice01.svg</value>
      <webElementGuid>d5cb659e-05ed-4bc9-af09-144c1640e8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgSku</value>
      <webElementGuid>9cfa0c2e-f75e-4f61-91c5-07094e929894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>be6e5b13-b795-4044-95c1-964b4e48d916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>150px</value>
      <webElementGuid>0428d064-15cc-4591-829e-2ec20b6722e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150px</value>
      <webElementGuid>2b25c2d2-bf08-412d-8cba-7d3ed608f4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mouse</value>
      <webElementGuid>1e3b74b4-6762-4333-bc84-c69e4d9c555a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgSku&quot;)</value>
      <webElementGuid>cdedd8ef-cf32-4b67-9cac-69100dca872f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='imgSku']</value>
      <webElementGuid>13b2fa1b-73e0-4845-8389-3a30cf481261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formAddProduct']/div[2]/div/div/div[2]/div/label/img</value>
      <webElementGuid>128db73a-f5a0-4b5b-a28a-5d990c9a241f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='icon']</value>
      <webElementGuid>a8294d57-fd2c-4fe0-8624-8b5ea84707b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/img</value>
      <webElementGuid>fe60163d-af6d-45de-84c2-de42cd5ad4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/cdn/gambar/addimage_backoffice01.svg' and @id = 'imgSku' and @alt = 'icon']</value>
      <webElementGuid>25f6863d-507c-4ea9-891b-d0f57545f400</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
