<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a97435ec-bfc3-4b1e-9146-61fd2ea30aff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myCaptcha > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myCaptcha']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog[name=&quot;Switch To Backoffice V2&quot;i] >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cc1dd790-42e9-49a2-8eef-2ce0026a37c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://adonis.kpntr.com/captcha/mini?miEbVa8r</value>
      <webElementGuid>52437c2d-488e-411c-a08f-8d4868936e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myCaptcha&quot;)/img[1]</value>
      <webElementGuid>77da5847-d427-4515-92ce-0d52d5d42da2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myCaptcha']/img</value>
      <webElementGuid>d50c7960-a819-41df-a6f3-ff43cff9043e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://adonis.kpntr.com/captcha/mini?miEbVa8r')]</value>
      <webElementGuid>e1a8f2ef-bdfa-43e6-83fa-575884717d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>c6cc45ad-7df7-4e0c-84d0-022ea150936b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://adonis.kpntr.com/captcha/mini?miEbVa8r']</value>
      <webElementGuid>e6333f00-a5ca-4e61-a670-98cd0a6a8eb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
