<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Baru_mk-2</name>
   <tag></tag>
   <elementGuidId>8fbcf3df-a079-4711-be86-b67a2169cfb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='laporanPenjualan']/ul/ul[2]/li/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Data Transaksi&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>cbe5bf23-d7b9-44f3-9060-893b1e00f4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mk-2</value>
      <webElementGuid>02a92bba-7416-4c1c-a6ac-8e677e19f00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                        Data Transaksi</value>
      <webElementGuid>f2443e9f-a66f-46ac-98c2-2118c08a0ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;laporanPenjualan&quot;)/ul[@class=&quot;nav&quot;]/ul[@class=&quot;nav&quot;]/li[@class=&quot;side-menu-not-active&quot;]/a[1]/p[@class=&quot;mk-2&quot;]</value>
      <webElementGuid>16fe67cb-ab93-408b-a919-c39a0cfe8142</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='laporanPenjualan']/ul/ul[2]/li/a/p</value>
      <webElementGuid>f864a1e6-fa02-4692-bd6d-597e8da1ad31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[2]/following::p[11]</value>
      <webElementGuid>29821611-8a34-497f-893c-5162a0981a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/following::p[30]</value>
      <webElementGuid>9b9b3382-d5a6-4e1c-9a93-80523dd28c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[3]/preceding::p[29]</value>
      <webElementGuid>0765537c-79ca-483a-9d5a-31d8ffc3edd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[4]/preceding::p[30]</value>
      <webElementGuid>7de54661-6b44-4e0c-8f1f-f55cec8024a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Data Transaksi']/parent::*</value>
      <webElementGuid>cf480799-6832-4911-850a-22e14acf1802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/ul[2]/li/a/p</value>
      <webElementGuid>b8a3e56b-5e60-4894-8a2c-4555f8e57652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '
                                                        Data Transaksi' or . = '
                                                        Data Transaksi')]</value>
      <webElementGuid>03bf5aa9-2358-4b67-8155-4a93442a455b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
