<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Daftar di sini_sebagai</name>
   <tag></tag>
   <elementGuidId>faac4b79-3fe3-41a1-92ef-136f7da277d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sebagai']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sebagai</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6c8f7c15-0800-42a3-9309-7556d3807240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sebagai</value>
      <webElementGuid>c1909a5c-a23d-44af-b879-641e2650e8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select mt-5-2 font-14-r</value>
      <webElementGuid>fda676ce-ff61-4531-ac9c-ec32a270e594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>myFunction()</value>
      <webElementGuid>29e7fd43-2dc6-4f26-94e4-e054df78799b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Owner
                            Staff
                        </value>
      <webElementGuid>b59b760c-fb49-466a-ac2b-43b61194acd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sebagai&quot;)</value>
      <webElementGuid>583f430c-c6a8-4ade-84e2-4f00a6693d83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sebagai']</value>
      <webElementGuid>ec02ec9d-9788-4836-88c8-48b3d426e557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='parent']/div/div/div/div/select</value>
      <webElementGuid>850299a3-4a63-4966-a7d2-9b601dfdc7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar di sini'])[1]/following::select[1]</value>
      <webElementGuid>b36f3f71-55b4-4012-abf2-34c980c9e7c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inggris'])[1]/following::select[1]</value>
      <webElementGuid>de57f6fb-01b1-4068-b3e3-13591b5a4198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/preceding::select[1]</value>
      <webElementGuid>fd5a319a-c97d-4c79-b8d2-3c2b2c543dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password?'])[1]/preceding::select[1]</value>
      <webElementGuid>1144cbf2-45e0-49da-b8be-c24956d2c044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a64f1c52-ddb3-44cf-9080-5d52edc6d5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'sebagai' and (text() = '
                            Owner
                            Staff
                        ' or . = '
                            Owner
                            Staff
                        ')]</value>
      <webElementGuid>d486c981-8e2e-4b76-bb48-4b1e56673c60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
