<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Menu Title Database</name>
   <tag></tag>
   <elementGuidId>f855d8ec-71c5-463f-92f5-5bc1b273b72a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.panel > a > p.upper-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='accordion']/li[5]/a/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Database&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>323a8dde-34b5-4433-b9cc-d9c0e4ccc243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>upper-text</value>
      <webElementGuid>21559663-f5c0-411b-8267-220caef1d4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Database </value>
      <webElementGuid>51ea3d0a-887e-459d-b93a-faa437c12c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion&quot;)/li[@class=&quot;panel&quot;]/a[1]/p[@class=&quot;upper-text&quot;]</value>
      <webElementGuid>e5ea179b-804d-457d-acc3-cacca61dc042</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='accordion']/li[5]/a/p</value>
      <webElementGuid>dcafc3aa-e3b0-4de0-ac53-37e49872391a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[1]/following::p[4]</value>
      <webElementGuid>52a73274-a1ed-4952-bb09-d9ae597fce27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading…'])[1]/following::p[6]</value>
      <webElementGuid>f15a5445-95b4-406f-8524-590f816a8525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[2]/preceding::p[15]</value>
      <webElementGuid>e082e1d8-bce4-4255-b9a7-b4b63e3038b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baru'])[3]/preceding::p[54]</value>
      <webElementGuid>7c2152c4-db0d-4656-9dca-7dc43009547c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Database']/parent::*</value>
      <webElementGuid>dfd3c901-a023-4432-97f6-7939b2d08ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/p</value>
      <webElementGuid>b816b200-22da-4061-bef5-7800be1baf75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Database ' or . = 'Database ')]</value>
      <webElementGuid>d41e3534-22a3-4c8d-9cc5-582214c50ad1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
